import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const postsDirectory = join(projectRoot, "docs", "posts");
const generatedFile = join(projectRoot, "docs", ".vuepress", "generated", "posts.ts");

const stripQuotes = (value) => {
  const trimmed = value.trim();
  if ((trimmed.startsWith("\"") && trimmed.endsWith("\"")) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
};

const parseFrontmatter = (source) => {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
  if (!match) return { values: {}, body: source };

  const values = {};
  let arrayKey = null;
  for (const rawLine of match[1].split(/\r?\n/)) {
    const line = rawLine.trimEnd();
    const arrayItem = line.match(/^\s+-\s+(.*)$/);
    if (arrayItem && arrayKey) {
      values[arrayKey].push(stripQuotes(arrayItem[1]));
      continue;
    }

    const field = line.match(/^([\w-]+):\s*(.*)$/);
    if (!field) continue;
    const [, key, rawValue] = field;
    if (!rawValue.trim()) {
      values[key] = [];
      arrayKey = key;
    } else {
      values[key] = stripQuotes(rawValue);
      arrayKey = null;
    }
  }

  return { values, body: source.slice(match[0].length) };
};

const toDateLabel = (date) => {
  if (!date) return "未注明日期";
  const [year, month, day] = date.split("-");
  return year && month && day ? `${year} 年 ${Number(month)} 月 ${Number(day)} 日` : date;
};

const getReadingLabel = (body) => {
  const characters = body.replace(/\s/g, "").length;
  return `约 ${Math.max(1, Math.ceil(characters / 350))} 分钟`;
};

const escapeForTypeScript = (value) => JSON.stringify(value);

const collectMarkdownFiles = async (directory, relativeDirectory = "") => {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const relativePath = join(relativeDirectory, entry.name);
    const absolutePath = join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await collectMarkdownFiles(absolutePath, relativePath)));
    } else if (entry.name.endsWith(".md") && entry.name !== "README.md") {
      files.push(relativePath);
    }
  }

  return files;
};

const preferredCategories = ["技术", "学习", "生活", "随笔"];
const files = (await collectMarkdownFiles(postsDirectory)).sort();

const posts = [];
for (const relativeFileName of files) {
  const source = await readFile(join(postsDirectory, relativeFileName), "utf8");
  const { values, body } = parseFrontmatter(source);
  const slug = relativeFileName.replace(/\.md$/, "").split(sep).join("/");
  const rawTags = values.tag ?? values.tags ?? [];
  const tags = Array.isArray(rawTags) ? rawTags : rawTags ? [rawTags] : [];
  posts.push({
    slug,
    path: `/posts/${slug}.html`,
    title: values.title || slug,
    description: values.description || "",
    date: values.date || "",
    dateLabel: toDateLabel(values.date || ""),
    reading: getReadingLabel(body),
    category: values.category || "随笔",
    tags,
  });
}

posts.sort((a, b) => a.date.localeCompare(b.date) || a.slug.localeCompare(b.slug));

const categories = [...new Set(posts.map((post) => post.category))].sort((a, b) => {
  const aIndex = preferredCategories.indexOf(a);
  const bIndex = preferredCategories.indexOf(b);
  if (aIndex === -1 && bIndex === -1) return a.localeCompare(b, "zh-CN");
  if (aIndex === -1) return 1;
  if (bIndex === -1) return -1;
  return aIndex - bIndex;
});
const tags = [...new Set(posts.flatMap((post) => post.tags))].sort((a, b) => a.localeCompare(b, "zh-CN"));

const output = `// This file is generated by scripts/generate-content.mjs.\n// Do not edit it directly; update the Markdown frontmatter instead.\n\nexport type BlogPost = {\n  slug: string;\n  path: string;\n  title: string;\n  description: string;\n  date: string;\n  dateLabel: string;\n  reading: string;\n  category: string;\n  tags: string[];\n};\n\nexport const posts: BlogPost[] = ${JSON.stringify(posts, null, 2)};\n\nexport const categories: string[] = ${escapeForTypeScript(categories)};\n\nexport const tags: string[] = ${escapeForTypeScript(tags)};\n`;

await mkdir(dirname(generatedFile), { recursive: true });
await writeFile(generatedFile, output);

const generatedRelativePath = relative(projectRoot, generatedFile).split(sep).join("/");
console.log(`Generated ${posts.length} posts, ${categories.length} categories and ${tags.length} tags -> ${generatedRelativePath}`);
